### ISSUE TITLE
How to load recently installed fonts without having to restart inkscape ?

### ISSUE THREAD

**Issue by ismnoiet** [inkscape/inkscape#8] opened 2016-02-12 07:28 UTC
Hi, is it possible to reload the list of fonts used by inkscape automatically once new font is added to the fonts directory, for example under ubuntu it is found at ``/home/[username]/.fonts`` directory.

Thank you in advance.

**Comment by fulldecent** [comment] 2016-04-10 22:29
Closing, this is a duplicate of https://bugs.launchpad.net/inkscape/+bug/981225

**Closed by fulldecent** 2016-04-10 22:29 UTC
Labels: duplicate
